name: Microservices with AWS and Fastapi
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
    - name: Install dependencies
      run:
        make install
    - name: Format code
      run:
        make format
    - name: Lint with pylint
      run:
        make lint
    - name: Test with pytest
      run:
        make test
      
    
